# Generated by Django 4.2.7 on 2023-12-04 00:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('data_registro', models.DateField(auto_now=True, verbose_name='Data de Registro')),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_divulgacao', models.CharField(max_length=50, verbose_name='Tipo de divulgação')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='imagem', verbose_name='Imagens')),
                ('divulgacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_da_divulgacao', to='servicos.divulgacao')),
            ],
        ),
        migrations.AddField(
            model_name='divulgacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divulgacao_do_tipo', to='servicos.tipodivulgacao'),
        ),
    ]
